### ISSUE TITLE
why this one assumed to be valid with "--snap_tol 1"?

### ISSUE THREAD

**Issue by hugoledoux** [tudelft3d/val3dity#103]
https://github.com/tudelft3d/val3dity/blob/e7bc46da66fa63faa8c128c5b07046d215e0da79/tests/test_user_input.py#L99

it's valid with 0.01, but not with 1... don't get the test.

**Comment by balazsdukai** [comment]
In `test_user_input` the goal is to test if val3dity behaves as expected with various in/valid arguments that the user could pass to it. Geometry validation is secondary in this module. Therefore the emphasis is on the `options_valid` parameters, and that for example `--snap_tol 0.01` is accepted, but `--snap_tol 1cm` is not.

Does this make sense?

**Comment by hugoledoux** [comment]
yes.

Although I know it's not possible since the library I use for command-line options will fail if anything else but a double is passed (if the casting fails then an exception is thrown). But leave it there, if I change the library it's useful
