### ISSUE TITLE
Version 2.0 Release

### ISSUE THREAD

**Issue by steveway1982** [tudelft3d/val3dity#113]
Hi, When will you be looking to release the  binaries for version 2?

Many Thanks,
Steve

**Comment by hugoledoux** [comment]
For Windows I assume you mean? Soon I guess. But I’m not a Windows users so always a bit of a pain, need to finds colleague. 

The web-application works already and it’s v2 in the background

**Comment by steveway1982** [comment]
Hi Hugo, yes for windows.  I understand your difficulties!

The issue we are trying to address, is that our client uses your website to verify our output, but we have an automated process, so by having the binary available (for windows) we can execute the task automatically.

Thanks,
Steve

**Comment by hugoledoux** [comment]
If your business depends on it, I suggest you compile it yourself, we offer a Visual Studio project if you use that. CMake should also work under Windows, although i haven’t tried.

**Comment by steveway1982** [comment]
That would be great, although the source code is still at version 1 - do you know when i will be able to download version 2 source code?

**Comment by hugoledoux** [comment]
Master branch is v2 (beta). All the code is in the repository.

**Comment by steveway1982** [comment]
Ok great.... downloaded it now, it seems that the CPP and HEADER files are missing for the following:

validate_shell_intersections
Shell

Are you able to commit these to github? 
cheers,
Steve

**Comment by hugoledoux** [comment]
Hmmm, these don’t exist anymore in v2.

The project file hasn’t been updated, just add all the files in /src/ and
it’ll work.

**Comment by hugoledoux** [comment]
Hello again, I'm always interested to know who is using val3dity and if it's useful for them, and how it could be improved. Could you let me know what is your company?

I gather that one way to improve it would be to provide Windows binary--that'll be done soon. But other feedback is welcome.

**Comment by steveway1982** [comment]
Hi Hugo,
Sure - The company name is Cyient and we are using val3dity to validate CityGML data that we are generating.  Our customer (who i cannot name) is also using this, which is the reason why we were keen to ensure we use the same tools to ensure consistency.

I managed to build the windows binary yesterday - was quite complicated with the dependencies and took a few hours.  Once thing that worries me, that when version updates happen in future, i will have to re-build the binary - maybe there could be dependency changes etc (I'm a Java guy, so Visual Studio is a whole new learning curve for me!)

If it is possible to have a windows binary built for your releases, that would be very useful.
But either way, appreciate what you have done, thank you!

Many Thanks,
Steve

**Comment by hugoledoux** [comment]
Great that it worked. The future releases will be minors, thus you'll be able to just press compile and it'll work.

If you think you set it up properly, you could perhaps submit your visualstudio project as a PR? That would help us, and others.

Cheers,
Hugo

**Comment by steveway1982** [comment]
I would share it, but i have come across an issue where the built EXE file, only works on machines that have Visual Studio installed.  So i guess i have something configured incorrectly.

Unfortunately for me, I'm not a microsoft or C++ developer - I have a java background so VS is difficult to understand.
