### ISSUE TITLE
Online vs Offline Windows exe JSON Report Descrepancy

### ISSUE THREAD

**Issue by steveway1982** [tudelft3d/val3dity#118]
Hi Hugo,

We have noticed, that the JSON report is hugely different between the online version of the tool, and the windows build.

Are you able to replicate this from your side?

Thanks,
Steve

**Comment by steveway1982** [comment]
Hi Hugo,

Further analysis, it seems the output is considerably different if the planarity_n_tol is set locally.  I am not sure how this is set online, but it defaults to 20.

Regards,
Steve

**Comment by hugoledoux** [comment]
default is 20 online, can't be changed. I could add it online though if there's a need for it. The idea is that 20 is good enough to be used, if you want to put a large value (180), click "ignore 204".
