### ISSUE TITLE
CGAL error

### ISSUE THREAD

**Issue by AgaBuilding3D** [tudelft3d/val3dity#121]
Hello,
I have analyzed the results of validation reports from desktop version of val3ditity 2.0.1. for Windows and
some files didn't validate because of error of CGAL library:

CGAL error: 
precondition violation!
Expression : ! K().collinear_3_object()(p,q,r)
File       : C:\dev\CGAL-4.11\include\CGAL/Kernel/function_objects.h
Line       : 2490
Explanation: 
Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html 

I think it could be wrong compilation under Windows because as I heard under Linux and macOS it runs.
I attached incorrect file.

[2014_N-34-105-D-a-4-3.zip](https://github.com/tudelft3d/val3dity/files/1574712/2014_N-34-105-D-a-4-3.zip)
I hope that you could check and fix this error.
Thank you very much for any help.

**Comment by steveway1982** [comment]
Hi Hugo, we are also facing the same issue.

Regards,
Steve

**Comment by hugoledoux** [comment]
can you both try the new binary 2.0.4? This should be fixed

**Comment by AgaBuilding3D** [comment]
I tried to validate some data sets with desktop version of val3ditity 2.0.4. for Windows and it seems to be fixed.
Thank you for this update.

**Comment by steveway1982** [comment]
I can confirm that.

Thanks Hugo – appreciate your efforts on resolving this bug.
