### ISSUE TITLE
Val3dity 2.0.2 error 303 and 306 issues

### ISSUE THREAD

**Issue by KraMar76** [tudelft3d/val3dity#122]
Hello
Great Thanks for solving error 104 issue !!!!!
Online validator in this case works perfect, I hope that you will be able to compile version for Windows soon :-)

During analysing  validation reports from new online val3ditity 2.0.2. I noticed new issues. 
Now errors 303 and 306 appears for cornet models.
Of course models are correct in my opinion.   
Please see attached zipped citygml file:
[0620_M-34-46-D-a-3-3.zip](https://github.com/tudelft3d/val3dity/files/1634456/0620_M-34-46-D-a-3-3.zip)

I hope that you could to take a look on this soon :-)
Thank you very much for any help.

**Comment by hugoledoux** [comment]
hmmm, are you sure it's the correct file?

I get only errors 204 for this model, both on macOS and on Linux, see for yourself:
http://geovalidation.bk.tudelft.nl/val3dity/reports/overview/d8640efa-2ff0-450e-89b6-654dc4f06e65

**Comment by KraMar76** [comment]
Dear Hugo
I ignored error 204 and errors 303 and 306  appeared.
Please see attached rapport json file.
In your control software detect error 204, shell is invalid and remainder
controls are held :-(
 
Marcin

**Comment by hugoledoux** [comment]
I see.

Ignoring 204 is tricky: it could create another error, this is possibly what is happening here. I hesitated to add that option to be honest, exactly because of this.

But I'll check soon to be sure everything is okay here.

**Comment by hugoledoux** [comment]
I looked quickly and isolated the 303 case (attached here), but it seems it's not noded properly and thus non-manifold, no? See:
https://www.dropbox.com/s/g6oxugmu9nu80na/2018-01-17%20at%2010.11.png?dl=0


[c2.gml.txt](https://github.com/tudelft3d/val3dity/files/1638312/c2.gml.txt)

**Comment by balazsdukai** [comment]
If I may chime in, @KraMar76 which CGAL version are you using?
I've just tested your file and I get 203,204 with default settings, and 202,303 with --ignore204
I've just compiled val3dity from the `master` and have cgal 4.7.4

**Comment by hugoledoux** [comment]
CGAL v4.10+ is now required, with eigen package, see README.

**Comment by KraMar76** [comment]
hmm, but what is incorrect?  I'm not able to find the error.
This is one shell and any polygon is outside this shell.
All polygons are forming shell. All polygons nodes are identical.
Please see attached screens.

**Comment by hugoledoux** [comment]
nothing is attached

**Comment by hugoledoux** [comment]
but 204 caused by vertices very close to each others: you might not be able to see the error.

http://geovalidation.bk.tudelft.nl/val3dity/docs/faq/#i-get-many-errors-203-and-204-but-my-planes-look-planar-to-me-why-is-that

**Comment by KraMar76** [comment]
Pictures I mentioned above

![303_error_b1bc_1](https://user-images.githubusercontent.com/35486131/35102457-502ca9f4-fc63-11e7-9b1a-8d507fe0803f.jpg)
![303_error_b1bc_2](https://user-images.githubusercontent.com/35486131/35102458-504916ac-fc63-11e7-8b50-6d3dfe17b8ec.jpg)
![303_error_b1bc_3](https://user-images.githubusercontent.com/35486131/35102459-50669466-fc63-11e7-8e89-cc87cf117d58.jpg)
![303_error_b1bc_4](https://user-images.githubusercontent.com/35486131/35102461-5087d1e4-fc63-11e7-83fb-0c2e104d2674.jpg)
![303_error_b1bc_5](https://user-images.githubusercontent.com/35486131/35102462-50a5afb6-fc63-11e7-84d1-73bc365646f2.jpg)
![303_error_b1bc_6](https://user-images.githubusercontent.com/35486131/35102463-50c6645e-fc63-11e7-9285-cbdf624d0740.jpg)

**Comment by KraMar76** [comment]
I checked nodes coordinates in gml file and all are the same.

Even if the polygon is not planar - 204 error 
but all coincident nodes in neighbouring polygons  are the same shell should be manifold

**Comment by hugoledoux** [comment]
okay, I tracked the error, and it is indeed an error. An extreme one due to precision: there are nearly collinear points (there is an unnecessary vertex where the arrow points) and because of the triangulation (I think) it reports a wrong 303 error...
https://www.dropbox.com/s/b8agji6toaydz0c/2018-01-23%20at%2010.06.png?dl=0

If you remove that vertex (which doesn't affect the shape of the building) then it's valid (as expected).

How to prevent such errors is not clear to me right now, I have to think about it. It's first time this happens to my knowledge.

**Comment by KraMar76** [comment]
Hi, thanks for the assist.
I understand your explanation but unfortunately I still haven't seen the error 303 here :-(
The vertex inside is maybe unnecessary but this is in both neighbour polygons. Nodes coordinates are identical so polygons vertexes should be identical too.  
Have you have a chance to take a look on 306 error? 
Haw do you see this ? 

Regards

**Comment by hugoledoux** [comment]
Not sure I follow you Marcin: you reported a dataset with errors 303 and 306.

I have found the error and fixed it, your dataset above now is 100% free of errors, including no 204 errors. I'll update the code, test it on different OSs, release 2.0.3, and describe the fix.

Again, thanks for spending time reporting these errors, I really appreciate.

**Comment by KraMar76** [comment]
I would like to apologize for my misunderstanding.
I thought that you had found an error in my data and tried to find this too 8-)

Thanks a lot for your help 👍 
I will be waiting for new release.

**Comment by hugoledoux** [comment]
v2.0.3 fixes this, released and web-app updated.

Windows will wait a bit, need to find an automatic build system (or switch myself to Windows; just joking not gonna happen)
