### ISSUE TITLE
Val3dity for Windows / Web-App Web Service  

### ISSUE THREAD

**Issue by kafedyk** [tudelft3d/val3dity#123]
Hello Hugo,

val3dity-windows-x64-v.2.0.1 compiled windows executable does not create json output files for some the input data files. It is related to "CGAL error" issue already raised.

Are you planning to release val3dity-windows-x64-v.2.0.2 with this issue fixed at any point soon?

We would greatly appreciate it!

Best regards,
Kasia

**Comment by hugoledoux** [comment]
My main "Windows compiler" is ill these days... so not this week I'm afraid.

I think indeed 2.0.2 would fix that issue, but I haven't tested it.

The webapp is updated though

**Comment by kafedyk** [comment]
Thanks for the response Hugo.

We would like to contribute and tried to compile one of the earlier version, unfortunate unsuccessfully. There were too many dependencies and what worked on the computer on which the source code was compiled did not work on other machines. 

We are gonna have to wait for your Windows Compiler to get well soon :)

Alternatively, would it be possible to create a web service that communicates with the server instead of submitting a FORM to the backend?
This will allow everyone to use the most recent webapp through for example FME without the need to compile the source code each time a new version is available.

Regards,
Kasia

**Comment by hugoledoux** [comment]
It's not in my plans to develop this, the web-app is there as a example to help and show what val3dity can do. But the code is open-source, you're free to build this yourself!
