### ISSUE TITLE
Error 305 - potential false positive reported by val3dity 2.0.1 and 2.0.3 

### ISSUE THREAD

**Issue by kafedyk** [tudelft3d/val3dity#124]
Hi Hugo,

Both val3dity 2.0.1 and the most recent online tool report error 305 for the attached 3D models.
The models seem to be built correctly and we are unable to identify the issue.

Your help will be much appreciated.

[305_errors.gml.txt](https://github.com/tudelft3d/val3dity/files/1657666/305_errors.gml.txt)

**Comment by hugoledoux** [comment]
The parsing of the GML indeed had a small error, other formats not affected.

Fixed, and in v2.0.4

**Comment by kafedyk** [comment]
Hi Hugo

Many thanks for looking into this.

Is there any chance windows complied 2.0.4 version will be released this week?

Thanks again!

**Comment by hugoledoux** [comment]
@kafedyk I managed to compile myself and the binaries are available. They are a bit different but should work: let me know please.

**Comment by kafedyk** [comment]
The windows compiled 2.0.4 version works a treat - Thank you!
