### ISSUE TITLE
Error 302 not found

### ISSUE THREAD

**Issue by kafedyk** [tudelft3d/val3dity#125]
Hi Hugo,

We have a model that we know is not watertight i.e. the GroundSurface dose not match the WallSurface at the top left corner of the building within the attached file. Val3dity dose not report any errors for this model, we expected error 302 to be reported in such cases?

Please could you have a look at this issue when convenient.

Many thanks!
[302_not_found.gml.txt](https://github.com/tudelft3d/val3dity/files/1657787/302_not_found.gml.txt)

**Comment by hugoledoux** [comment]
2.0.3 does report 302, see here: 

http://geovalidation.bk.tudelft.nl/val3dity/reports/overview/be6c9caa-63dd-4051-8c3a-26ee2adb5332
