### ISSUE TITLE
should <gml:Polygon> be validated?

### ISSUE THREAD

**Issue by hugoledoux** [tudelft3d/val3dity#129]
if that's the only geometry in a Feature for instance

**Comment by balazsdukai** [comment]
Are there any arguments against it?

**Comment by hugoledoux** [comment]
Yes: more work for me!

The issue is that parsing them means checking first if these are not part of the 5 geom types already checked... I'll do it.

**Comment by hugoledoux** [comment]
OK, I coded the `gml:Polygon` (see 0fd1fb33ef8c05658052992d5faa41fd918f94e8) but then realised that this is just the beginning, Polygons are like an alias for a plethora of GML types for surfaces, eg `gml:PolygonType`, `gml:CompositeSurfaceType`, `gml:SurfaceType`, `gml:TinType`, `gml:OrientableSurfaceType`.

So I went for a walk, thought about it, and decided that it's not worth the (massive) effort.

So I'm closing the issue.
