### ISSUE TITLE
/usr/bin/ld: CMakeFiles/val3dity.dir/src/main.cpp.o: undefined reference to symbol '_ZN5boost6system15system_category

### ISSUE THREAD

**Issue by vinodvin369** [tudelft3d/val3dity#130]
please help to solve these errors.
[ 11%] Built target thirdparty
[ 16%] Building CXX object CMakeFiles/val3dity.dir/src/geomtools.cpp.o
[ 22%] Building CXX object CMakeFiles/val3dity.dir/src/input.cpp.o
[ 27%] Building CXX object CMakeFiles/val3dity.dir/src/main.cpp.o
[ 33%] Building CXX object CMakeFiles/val3dity.dir/src/validate_prim_toporel.cpp.o
[ 38%] Building CXX object CMakeFiles/val3dity.dir/src/validate_shell.cpp.o
[ 44%] Linking CXX executable val3dity
/usr/bin/ld: CMakeFiles/val3dity.dir/src/main.cpp.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.62.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/val3dity.dir/build.make:466: recipe for target 'val3dity' failed
make[2]: *** [val3dity] Error 1
CMakeFiles/Makefile2:680: recipe for target 'CMakeFiles/val3dity.dir/all' failed
make[1]: *** [CMakeFiles/val3dity.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hugoledoux** [comment]
That doesn't tell me much, besides that BOOST system seems to complain when it tries to link to it. D you have a full boost installed? 

If you follow the steps mentioned under linux (Ubuntu?) then it works.

Give here the full print of the console, perhaps it can help
