### ISSUE TITLE
Building with lod1Solid and lod2Solid geometries is wrong or there is a bug?

### ISSUE THREAD

**Issue by arruga** [tudelft3d/val3dity#133]
Hi Hugo,
I'm generating buildings with lod1 and lod2 solid geometries but val3dity 2.1.0 and 2.0.4 complain with BUILDINGPARTS_OVERLAP message. I think it should not compare geometries at different levels of detail. Maybe my gml is wrong but CityDoctor and 3D City Database have validated it. 
Thank you very much for this software. It is really useful. 
This is a tiny example:
[lod1ilod2.zip](https://github.com/tudelft3d/val3dity/files/2101146/lod1ilod2.zip)

**Comment by hugoledoux** [comment]
Indeed it shouldn't, but I'm afraid it does indeed... 

You're the first one to test val3dity with buildings at different LoDs I'm afraid!

I need to modify the CityGML parser to identify this, and that could take some time. So may I suggest you just split the file into 2 files for the time being? I'll try to fix at some point.

Thanks for reporting that mistake.

**Comment by hugoledoux** [comment]
they say "better later than never", don't they?

It's fixed, mostly because I avoided modifying the citygml parser altogether: citygml support is gone from val3dity v2.3.0. 

But all is working with CityJSON 🚀
