### ISSUE TITLE
Application error with Win-x64 build

### ISSUE THREAD

**Issue by hlg** [tudelft3d/val3dity#140]
I am using the win-x64 build of version 2.0.4 and get an application error after output of the validation parameters.

Exception code: 0xc0000005
Fault offset: 0x000000000009b940

Validation of the same GML succeeds without errors in version 1.3.1.
Will isolate a test case and post the file here.

**Comment by hlg** [comment]
There seems to be an issue with namespaces. The failing file has a lot of unused namespaces defined:

    <CityModel xmlns:addr="http://www.w3.org/2005/08/addressing" xmlns:app="http://www.opengis.net/citygml/appearance/3.0" xmlns:bldg="http://www.opengis.net/citygml/building/3.0" xmlns:brdg="http://www.opengis.net/citygml/bridge/3.0" xmlns:con="http://www.opengis.net/citygml/construction/3.0" xmlns:dyn="http://www.opengis.net/citygml/dynamizer/3.0" xmlns:fes="http://www.opengis.net/fes/2.0" xmlns:furn="http://www.opengis.net/citygml/cityfurniture/3.0" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gen="http://www.opengis.net/citygml/generics/3.0" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gmlcov="http://www.opengis.net/gmlcov/1.0" xmlns:grp="http://www.opengis.net/citygml/cityobjectgroup/3.0" xmlns:gts="http://www.isotc211.org/2005/gts" xmlns:ifc="https://ifc2citygml.github.io/1.0" xmlns:luse="http://www.opengis.net/citygml/landuse/3.0" xmlns:ns22="http://www.opengis.net/citygml/pointcloud/3.0" xmlns:om="http://www.opengis.net/om/2.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:rel="http://www.opengis.net/citygml/relief/3.0" xmlns:samp="http://www.opengis.net/sampling/2.0" xmlns:sampspat="http://www.opengis.net/samplingSpatial/2.0" xmlns:sos="http://www.opengis.net/sos/2.0" xmlns:swe="http://www.opengis.net/swe/2.0" xmlns:swes="http://www.opengis.net/swes/2.0" xmlns:tran="http://www.opengis.net/citygml/transportation/3.0" xmlns:tsml="http://www.opengis.net/tsml/1.0" xmlns:tun="http://www.opengis.net/citygml/tunnel/3.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/3.0" xmlns:ver="http://www.opengis.net/citygml/versioning/3.0" xmlns:wsn="http://docs.oasis-open.org/wsn/t-1" xmlns:wtr="http://www.opengis.net/citygml/waterbody/3.0" xmlns:xal="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/citygml/3.0">

They look ok to me though. As soon as the unused ones are removed, everything works fine:

    <CityModel xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gen="http://www.opengis.net/citygml/generics/2.0" xmlns="http://www.opengis.net/citygml/3.0">

**Comment by hlg** [comment]
We could further narrow this down to this namespace:

    xmlns:gmlcov="http://www.opengis.net/gmlcov/1.0"

The application crash can be reproduced by adding this innocent namespace to an otherwise valid GML file. Could reproduce it on MacOS as well.

**Comment by hugoledoux** [comment]
thanks a lot for reporting this bug and for isolating it.

d6586f98a5517adda7cd78f95262fbe0bfd616c4 solves it, and will be in the next patch release (2.1.1)

Basically, the identifier for namespaces are URLs, and `"http://www.opengis.net/gmlcov/1.0"` has for subset `"http://www.opengis.net/gml"`, and I used string subset to find the good one. So if you put that gmlcov after the gml one, it crashed....
