### ISSUE TITLE
Pullrequest

### ISSUE THREAD

**Issue by vvmruder** [tudelft3d/val3dity#143]
Hi together,

I have some suggestions on Docker usage for your project in a local branch. I would like to offer you this via a pull request. Can you give right to create new branch and pull requests on this repo to me? Then you could review the code.

@balazsdukai: We had contact about this before.

If you have another preferred way of collaboration just let me know.

Regards
Clemens

**Comment by balazsdukai** [comment]
Hi Clemens, this was quick, thanks!
Opening a PR would be the preferred way. I believe the regular way to do this on github is to fork the repository, work on that, and submit the PR to the original from the fork. This is a lengthy, but thorough tutorial for the process: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github 
Let me know if this doesn't help.

**Comment by vvmruder** [comment]
Thanks. You can find the PR here: #144 

This issue can be closed.
