### ISSUE TITLE
request to view coordinates (x,y and z) 

### ISSUE THREAD

**Issue by senthilkumarelectronics** [tudelft3d/val3dity#146]
Hi Hugoledoux, This software is great to check 3D primitives. I am trying to generate reports for sample file. But unfortunately i am not able to get location coordinate of errors.
Is it possible to get location of error coordinate along with id, error number. 
which command needs to used to generate reports with coordinate?
I am using Executable provided in the website ( val3dity2.1)
 I used below command to generate html report:       

 >val3dity` S2.obj -r `D:\3dBuilding\Output

But  error location coordinate is not available. Attached snapshot for your reference.
I am using  Windows  Operating System version  10 64 bit 
![samplrereport](https://user-images.githubusercontent.com/30506856/69145742-5e61ff00-0af4-11ea-840b-df856f46fbb6.PNG)

**Comment by hugoledoux** [comment]
I don't report the location x-y-z but the ID is that of the face involved. If a gml:id is present it'll be reported there, if none then the ID is the position in the gml file, starting at 0.

**Comment by senthilkumarelectronics** [comment]
Thanks for the reply
