### ISSUE TITLE
Ignore or approve Implicit Geometry

### ISSUE THREAD

**Issue by CWisse** [tudelft3d/val3dity#149]
When validating a file existing of both solids and implicit geometries, all implicit geometries except the one with the geometry are rejected with code 609 - Object has no geometry. This can be explained, but it contaminates the entire result of the validation. Is it possible to implement ignoring or approving those features without geometry?

**Comment by hugoledoux** [comment]
Hmmm, I understand.

I'll have an option `--ignore609` in the next version. Other options are: http://geovalidation.bk.tudelft.nl/val3dity/docs/usage/#options-for-the-validation

Validating the implicit geometry makes little sense, although it should be done once at least for one file... I'll think about how this can be done.

Next version is probably ~end February.

**Comment by CWisse** [comment]
That will help me a lot.

Except when there's accidentally another feature without geometry in the file. It will not be found when Val3dity is ignoring 609. So probably ignoring 609 only when the feature is implicit geometry will give a better result.

**Comment by hugoledoux** [comment]
Full support for GeometryTemplates added for v2.2 (3914a748e4fcad63cad3f273a4373878c6caf7ec)

This solves all the issues above I reckon, and the GeometryTemplates themselves are also validated and appear in the report. You can try it soon when released.

One caveat: only CityJSON is supported. I have decided to phase out the support for CityGML (all versions). It's still there in v2.2 but I will not work on the code. I will remove it from v2.3+. 

Implementing this would have taken several days, and I can't justify it anymore. 

Just convert your files to CityJSON (https://www.cityjson.org/help/users/conversion/), I'll always maintain a full CityJSON parser!
