### ISSUE TITLE
Possibility to report OBJ_IDs only

### ISSUE THREAD

**Issue by comuniofuchs** [tudelft3d/val3dity#155]
Hi, 

Is there a possibilty to only get a list of invalid OBJ_ID's only? Next to Val3dity we're also using fme and AutoCAD to validate solids. There is no easy way to merge the results of all validations in one file. So a simple list with the OBJ_IDS would be very helpful. 

Best regards

Simon

**Comment by hugoledoux** [comment]
You could just parse the report and extract those, writing specific options for this is not in my plans, sorry.
