### ISSUE TITLE
ERROR code source?

### ISSUE THREAD

**Issue by MattSmillie** [tudelft3d/val3dity#156]
Hiya, just a question on where you guys get the code numbers from which you use in the output. I'm just working on another validation tool and want to be consistent with your error codes and definitions. I just have noticed the CityGML specific tests (601 and 609) look to be missing a few numbers and it got me thinking that val3dity is getting the codes form another source. Or perhaps these are old tests which have been deprecated in the past?

**Comment by hugoledoux** [comment]
We don't get them from anywhere, our own codes they are.

**Comment by hugoledoux** [comment]
I think I dropped some codes (got merged) and didn't want to change all previous, therefore some are missing.

**Comment by MattSmillie** [comment]
Thanks for the answer. Helps me to move forward. Great project guys
