### ISSUE TITLE
problem running Val3dity as library (in WSL)

### ISSUE THREAD

**Issue by Lkeurentjes** [tudelft3d/val3dity#172]
When Using Val3dity as a library (in cmakelist.txt as `target_link_libraries([projectname] LINK_PUBLIC val3dity)`). I get the following error:
```
/mnt/c/Users/Lisa/Documents/Github/val3dity/thirdparty/tclap/MultiArg.h: At global scope:
/mnt/c/Users/Lisa/Documents/Github/val3dity/thirdparty/tclap/MultiArg.h:228:21: error: expected unqualified-id before ‘const’
228 |         MultiArg<T>(const MultiArg<T>& rhs);
|                     ^~~~~
/mnt/c/Users/Lisa/Documents/Github/val3dity/thirdparty/tclap/MultiArg.h:228:21: error: expected ‘)’ before ‘const’
228 |         MultiArg<T>(const MultiArg<T>& rhs);
|                    ~^~~~~
|                     )
```
I can easily discard the error by comment the private part of Multiarg.h & Valuearg.h:
```
//private:

//	/**
//	 * Prevent accidental copying
//	 */
//	MultiArg<T>(const MultiArg<T>& rhs);
//	MultiArg<T>& operator=(const MultiArg<T>& rhs);
```
```
//private:
//       /**
//        * Prevent accidental copying
//        */
//       ValueArg<T>(const ValueArg<T>& rhs);
//       ValueArg<T>& operator=(const ValueArg<T>& rhs);
}
```
But I cannot find why this error should occur. I run cmakelist on a windows dekstop through WSL. with the following versions used:
- Ubuntu 22.04.2 LTS
- Cmake 3.23.0
- CGAL 5.4-1
- Geos 3.11.2
- gdb 12.1

**Comment by Lkeurentjes** [comment]
Expiernced the same issue on a Ubuntu native 22.04.2, find out it has to do with g++-11 version ([see this issue](https://sourceforge.net/p/tclap/bugs/33/).

He solved the bug by: Fixed in [[commit]](https://sourceforge.net/p/tclap/code/ci/b8e464f450aa35b61b56763644bc9c0a9315e2e1/) for 1.4, and [[commit]](https://sourceforge.net/p/tclap/code/ci/52a118c0edb20f64e8da88dc9d0bfee63f2232ac/) for 1.2. So probably Tclap needs to be updated (or maybe in the readme that you need a lower version of g++)

**Comment by hugoledoux** [comment]
I put v1.2.5 which should fix the issue, can you confirm it works for you?

this branch: https://github.com/tudelft3d/val3dity/tree/tclap-gcc

**Comment by Lkeurentjes** [comment]
Yes! It works now thanks!
