### ISSUE TITLE
Val3dity Report error id MultiSolid and CompositeSolid

### ISSUE THREAD

**Issue by Lkeurentjes** [tudelft3d/val3dity#175]
Should the id of a (ring)error for a MultiSolid an CompositeSolid not be `solid:0 -- shell:0 -- face:0` instead of `shell:0 | 0 -- face:0`?

**Comment by hugoledoux** [comment]
yes, give me a test file please I'll fix this

**Comment by Lkeurentjes** [comment]
[MSolidCube_ringerrrors.json](https://github.com/tudelft3d/val3dity/files/13450950/MSolidCube_ringerrrors.json)
had 3 errors with this ID problem
