### ISSUE TITLE
Develop New report ID for Tu3djson

### ISSUE THREAD

**Issue by Lkeurentjes** [tudelft3d/val3dity#183]
I tested the new report with several files and there are still some problems with the Id's (locations) of the errors. It lost some of the information. For example when testing all these files with error 101:
[101_MSurf.city.json](https://github.com/user-attachments/files/15784445/101_MSurf.city.json)
gives `"id": "-1|face=0"` -> unclear where the -1 comes from, but otherwise the error id location is clear (& it is the same for tu3djson)
[101_Solid.city.json](https://github.com/user-attachments/files/15784446/101_Solid.city.json)
gives `"id": "coid=id_1|geom=0|shell=0|face=0"` which is correct, but when you translate this to a [tu3djson](https://github.com/user-attachments/files/15784661/101msolid.json) it gives  `"id": "0|face=0"`--> but should also mention (/at least it did in the old report) on which shell the error is, In this case it is okay cause there is only one shell, but when there are multiple inner shells it doenst tell on which shell the face "0" is broken 
[101_MSolid.city.json](https://github.com/user-attachments/files/15784444/101_MSolid.city.json)
gives `coid=id_1|geom=0|solid=0|shell=0|face=0` which is correct, but when you translate this to a [tu3djson](https://github.com/user-attachments/files/15784758/101solid.json) it gives `"id": "-1|face=0"`, which is not very helpfull again

and this problem that for tu3djson only the "face" occurs happens on Ring level, polygon level, shell level

**Comment by Lkeurentjes** [comment]
fixed the new report in the forked repository and also found the -1 form the multisurface and changed it

**Comment by hugoledoux** [comment]
can you please create a PR with your changes? it's easier for me I can just merge

**Comment by hugoledoux** [comment]
First issue above (MSurf having no coid or geomid) is fixed f7b06d4d3e1ee9923f2a16050a0d51b42e4e6ab5

**Comment by hugoledoux** [comment]
Reporting of IDs is fixed 774f3e8ff17ab21bf7ac06a90910e8c0765d6044

**Comment by Lkeurentjes** [comment]
yes! I think they are alle fixed for all my test cases
