### ISSUE TITLE
libc++abi: terminating due to uncaught exception for tu3djson on MacBook

### ISSUE THREAD

**Issue by Lkeurentjes** [tudelft3d/val3dity#189]
When validating tu3djson files on MacBook, for example:
[01_BAGtu3d.json](https://github.com/user-attachments/files/17489586/01_BAGtu3d.json)

I get:
libc++abi: terminating due to uncaught exception of type nlohmann::json_abi_v3_11_2::detail::type_error: [json.exception.type_error.302] type must be array, but is number (according to bt the error is thrown in parse_tu3djson())

But it is only for some of the tu3djson, both when compiling val3dity on its own and when used as a library. The same files don't have problems on Linux. I use the latest version of val3dity an run it in clion. On Both computes I use CGAL 6.0 . The MacBook is on 14.4.1 (Sonoma)

**Comment by hugoledoux** [comment]
the input file is not a valid tu3djson file (syntax-wise)... val3dity is not robust against this.

1. the Solid has the wrong number of [] (one level was missing)
2. a "properties" was outside the "features.

if you fix those the file is fine, I attach it if you want to see
[01_BAGtu3d.json](https://github.com/user-attachments/files/17544867/01_BAGtu3d.json)
