### ISSUE TITLE
validating complex solid

### ISSUE THREAD

**Issue by chenkianwee** [tudelft3d/val3dity#22]
Hi, I have been using val3dity to validate the citygml files that I have generated. It is a very useful tool. However, I am facing trouble validating this file that I have generated (as shown in the figure ). I keep getting the error "WRONG_ORIENTATION_SHELL" from val3dity. As you can see from the figure, the normal of each polygon is already pointing outwards. Thus, I cannot really figure out what is really wrong with my geometry. I have checked numerous time, so I thought I could maybe get some help from val3dity? I have also attached the citygml file here. Thanks.

<img width="955" alt="tower" src="https://cloud.githubusercontent.com/assets/13062600/22426005/9a6e8474-e738-11e6-94d0-ab286ee60de6.png">

[example3_part.txt](https://github.com/tudelft3d/val3dity/files/739137/example3_part.txt)

**Comment by hugoledoux** [comment]
Hi, many thanks for pointing this out. I've been testing it and indeed this is indeed a bug, and having that file is very useful to debug.

I'll try to fix this ASAP and let you know.

**Comment by hugoledoux** [comment]
okay, that was easy: fixed. aa065f082a34353c250e1b9e35167e119edcbddd
Pushed to master branch also, let me know if you encounter that again, but I think it's fine now.

Cheers
