### ISSUE TITLE
an issue of false positive errors in Error type: 203 & 204

### ISSUE THREAD

**Issue by GovardhanAvi** [tudelft3d/val3dity#33]
Hi val3dity team,

Thanks for providing such excellent tool for validating the CityGML 2.0 3D models geometrically.

We would like to request you to please have a look into below issue.

Currently we are using val3dity tool 1.2/1.3.1 version. We are facing an issue of false positive errors for Error type:  203 NON_PLANAR_POLYGON_DISTANCE_PLANE) and 204 (NON_PLANAR_POLYGON_NORMALS_DEVIATION), though these surfaces are in planar.

Herewith we are attaching some sample buildings for your quick reference, which are having planar surfaces. These have been validated through FME planer checks and it is also showing planar in Micro Station software.

Can you please give your valuable comments on this.

We look forward to your quick response.

**Comment by hugoledoux** [comment]
FME 3D validation transformer is actually a wrapper around val3dity, so I would be very surprised if it returns no error for this file. 

First, something is planar *according to a tolerance*, and in val3dity you can setup the tolerance you want (option `--planarity_d2p 0.1` for a 10cm tolerance). Second, MicroStation surely uses a tolerance: what did you use?

Both errors are explained in that [file](https://github.com/tudelft3d/val3dity/blob/master/errors_description/errors_description.md). Also

For error 203, from your example, you used 0.01m but many of the vertices are at 0.15m from the plane that is fitted, but this is non-planar. Some are at about 30cm also, it's in the report generated. You won't be able to visualise these I'm afraid, but I'm rather certain the code is correct (but possible there is an error, but these errors are very frequent).

For error 204, it's more complex. Basically, a surface is first check for 203, if valid then 204 is checked. By definition, if an error 204 is reported then all the vertices are within 1cm (tolerance you used), thus you wouldn’t be able to visualise them. That usually means that you have vertices that are very close (say 0.2mm) and thus it’s easy to get a 90degree deviation. 

Hope that helps.

**Comment by GovardhanAvi** [comment]
Hi Hugo,

Thanks for your quick reply.

We will recheck the data as you suggested and get back to you.

Thanks once again

Regards 
Govardhan 

Sent from my iPhone

> On 02-May-2017, at 8:43 PM, Hugo Ledoux <notifications@github.com> wrote:
> 
> FME 3D validation transformer is actually a wrapper around val3dity, so I would be very surprised if it returns no error for this file.
> 
> First, something is planar according to a tolerance, and in val3dity you can setup the tolerance you want (option --planarity_d2p 0.1 for a 10cm tolerance). Second, MicroStation surely uses a tolerance: what did you use?
> 
> Both errors are explained in that file. Also
> 
> For error 203, from your example, you used 0.01m but many of the vertices are at 0.15m from the plane that is fitted, but this is non-planar. Some are at about 30cm also, it's in the report generated. You won't be able to visualise these I'm afraid, but I'm rather certain the code is correct (but possible there is an error, but these errors are very frequent).
> 
> For error 204, it's more complex. Basically, a surface is first check for 203, if valid then 204 is checked. By definition, if an error 204 is reported then all the vertices are within 1cm (tolerance you used), thus you wouldn’t be able to visualise them. That usually means that you have vertices that are very close (say 0.2mm) and thus it’s easy to get a 90degree deviation.
> 
> Hope that helps.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


Disclaimer | The information contained in this electronic message (including any attachments) is intended for the exclusive use of the addressee(s) and may contain confidential or privileged information.If you have received this in error, please notify the sender immediately and delete the material from your machine. Any  action including review, retransmission, dissemination of this email or the attachments present along with the email by persons or entities other than the intended recipient is prohibited.

**Comment by hugoledoux** [comment]
I've added a short description so that everyone can read it:

http://geovalidation.bk.tudelft.nl/val3dity/faq#i-get-many-errors-203-and-204-but-my-planes-look-planar-to-me-why-is-that

Hope that helps.
