### ISSUE TITLE
How to heal Error 203 & 204 types without triangulate of surfaces

### ISSUE THREAD

**Issue by GovardhanAvi** [tudelft3d/val3dity#34]
We have created realistic roof surfaces from LiDAR point cloud data with planar tolerance of 3 cm, most of the data is turned into Error type:  203 (NON_PLANAR_POLYGON_DISTANCE_PLANE) and 204 (NON_PLANAR_POLYGON_NORMALS_DEVIATION).

We are able to identify above errors with val3dity tool. 

But, how to heal these errors  {Error type:203 (NON_PLANAR_POLYGON_DISTANCE_PLANE) and 204 (NON_PLANAR_POLYGON_NORMALS_DEVIATION)} types without triangulating of surfaces?

Please anyone can suggest a logic for aforesaid problem.

Regards
Govardhan

**Comment by hugoledoux** [comment]
That paper could certainly help you:

https://link.springer.com/chapter/10.1007/978-3-319-55702-1_78
