### ISSUE TITLE
consider using an alternative character instead of `&` in the report

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#39]
On v2.
Run `val3dity /val3dity/data/gml/csol2.gml -r csol2_rep.xml`.
The report doesn't open in a web browser (Firefox or Chromium), due to an XML parsing error of the `&` character. In the report it looks like:

```
		<Error>
			<code>501</code>
			<type>INTERSECTION_SOLIDS</type>
			<id>1 & 2</id>
			<info></info>
		</Error>
```

Maybe a `,` could be used instead?

**Comment by hugoledoux** [comment]
done
