### ISSUE TITLE
POLY parser stalls on a hole definition with boundary marker

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#49]
On branch `v2_test`
Run `$ pytest -v -k "test_valid_poly[valid_2.poly]"`
The cube has a hole defined in it according the the [.poly documentation](http://wias-berlin.de/software/tetgen/1.5/doc/manual/manual006.html#ff_poly) but val3dity hangs when reading the file.

A sample from the file:
```
...
8 0.2 0.2 1.0
9 0.5 0.2 1.0
10 0.8 0.2 1.0
6 0
2 1 0           # a facet with two polygons and one hole, no boundary marker
4 4 5 6 7       # polygon 1
4 7 8 9 10      # polygon 2, this is the hole
1 0.7 0.3 1.0   # a point in polygon 2 to mark the hole
1 0
4 0 3 2 1 
...
```

Furthermore, the files in `/data/parse_poly/` confirm that this problem occurs in a case when there is,

+ a cube, not in the case of a single 3D polygon, 
+ a hole defined in a facet,
+ the facet definition `2 1 0` also contains a digit for the boundary marker, even though that is `0`

**Comment by hugoledoux** [comment]
yeah, I didn't implement all the specs of POLY, but I didn't say so. The specs are actually ambiguous... but I state that I support POLY and that is not true. 

No one uses POLY except me (and now you!) for testing/debugging, so I should just remove it from the doc but let it as a valid input.

and yes POLY must be without comments, and no boundary markers.
