### ISSUE TITLE
rounding of values in validation checks

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#53]
On branch v2_test.
`test_204_valid` fails to report valid, with surface normal difference is 0.99971° (using tolerance 1°)
What is a reasonable precision to expect in this case?

**Comment by hugoledoux** [comment]
that should return invalid, I'll look into it

**Comment by balazsdukai** [comment]
Yes, it does return invalid, but I expected valid, because the normal difference is 0.00029° below the threshold :-). Which is probably an unreasonable expectation, but I thought its a good opportunity to ask what would be reasonable to expect?

**Comment by hugoledoux** [comment]
it returns valid here... for you still invalid? (not sure what was changed in meantime)

**Comment by balazsdukai** [comment]
I've changed the tests a bit to reflect the updates on the 204 error. Now the tests are:

```yaml
  "204_valid_1": Unit cube with a hump (+0.00699) in the top face, which results in an 1.00114° normal difference
  "204_valid_2": Unit cube with a depression (-0.00699) in the top face, which results in an 1.00114° normal difference
  "204_1": Unit cube with a vertical fold (0.0099) in the top face
  "204_2": Unit cube with a vertical fold (0.0009) in the top face
```

All of them passes for me, which means the first to returns valid, the second two returns invalid.
