### ISSUE TITLE
remove POLY support from the doc

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#55]
Remove POLY support from the doc, because it is only used for testing ( #49 )

- [ ] remove it from the Accepted input section
- [ ] remove the `--ishell` option

**Comment by hugoledoux** [comment]
I just realised that there's the option `--ishell <string>` though... hmmm, think I can hide it from the help menu though.

**Comment by hugoledoux** [comment]
okay, fixed with 976da184d3cb8e01752626fad0e57941473e356b & 56ab2243eca31fa48380cdd2c9079ce034ab1032

removed from the doc and from the --help, one can use POLY as input and with --innershell but not exposed

**Comment by balazsdukai** [comment]
Ah, not sure if this was necessary, but there is a "dangling" POLY in the Accepted input section in the docs. 
9bc6efe fixes that once its merged, but I wait with the PR couz there might be other improvements later as well
