### ISSUE TITLE
error 309 not reported for OFF and OBJ

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#58]
On branch v2_test
Run `pytest -k "309" -v`
Each of the two files, 309.off and 309_1.obj contain one unused vertex. This should trigger a 309 error but it doesn't.

**Comment by hugoledoux** [comment]
error 309 is not really an error, since it doesn't influence the downstream applications. It's more a warning, but not necessary I reckon. So I removed it (f562cfc316f8dd21845c76a1bf78869870d27603_
