### ISSUE TITLE
Segmentation fault at an incorrect CityGML namespace declaration

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#75]
The Buildings namespace is declared as v1.0 in a CityGML v2.0 file `/val3dity/data/test_file_format/invalid_citygml_3.gml`  and validating it results in segmentation fault.

The section from the gml
```
xmlns:bldg="http://www.opengis.net/citygml/building/1.0" 
# should be:
xmlns:bldg="http://www.opengis.net/citygml/building/2.0"
```

**Comment by balazsdukai** [comment]
After our discussion at #74 about schema validation, do you want to handle this case @hugoledoux ? Because b07639098de913c57c7662aa697529899f740f50 removed the test, but I can add it again.

**Comment by hugoledoux** [comment]
that file doesn't exist in the repo?

**Comment by balazsdukai** [comment]
It does, but its history. With b076390 I removed it because it seem irrelevant due to #74 , and I wanted to leave as little litter as possible. I guess I should put it back then?

**Comment by hugoledoux** [comment]
no, just close the issue then
