### ISSUE TITLE
Segmentation fault at a CityJSON with an empty primitive

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#76]
The [CityJSON file](https://github.com/tudelft3d/val3dity/blob/v2_test/data/test_empty/empty_primitive.json) has a CompositeSolid where one of the Solids is missing. Validating it results in a segmentation fault.

**Comment by hugoledoux** [comment]
solved for MSol and CSol 27cf8278e43d1500661804efc346346ad6a67b28

But perhaps for other cases it's not 100% correct, so if you think of other cases please be mean
