### ISSUE TITLE
error 902 reported as 101 in an OFF

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#77]
The [OFF file](https://github.com/tudelft3d/val3dity/blob/v2_test/data/test_empty/empty_primitive.off) has no face definitions, just the vertices are defined. Validating it as
`$ ./build/val3dity data/test_empty/empty_primitive.off -p Solid` returns 101

The validation of a [very similar OBJ with missing faces](https://github.com/tudelft3d/val3dity/blob/v2_test/data/test_empty/empty_primitive.obj) returns 902 however.

**Comment by hugoledoux** [comment]
fixed: 93c115f1de9c458073095345c35d89abd7c3657a

901 is returned for that case since 28 surfaces are declared but not defined.

for a case where 0 surfaces are declared, eg below, then 902 is correctly returned
```
OFF
16 0 0
0 0 0
1 0 0
1 1 0
0 1 0
0 0 1
1 0 1
1 1 1
0 1 1
0.2 0.2 0.5
0.8 0.2 0.5
0.8 0.8 0.5
0.2 0.8 0.5
0.2 0.2 1
0.8 0.2 1
0.8 0.8 1
0.2 0.8 1
```
