### ISSUE TITLE
Console output and exit status

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#80]
Consider the following code snippet in python3.5:

```python
import subprocess, pprint

data = ["./data/test_valid/composite_solid.json"]
val3dity = ["./build/val3dity"]
options = ["--verbose"]

command = val3dity + options + data

proc = subprocess.run(command,
                      stdout=subprocess.PIPE,
                      stderr=subprocess.PIPE,
                      universal_newlines=True,
                      timeout=6)

pprint.pprint(proc.stdout) # standard output
pprint.pprint(proc.stderr) # error output
pprint.pprint(proc.returncode) # exit status
```
Or a second case where val3dity exits with and error:
```python
import subprocess, pprint

data = ["./data/test_valid/composite_solid.json"]
val3dity = ["./build/val3dity"]
options = ["--planarity_n_tol 18degree"]

command = val3dity + options + data

proc = subprocess.run(command,
                      stdout=subprocess.PIPE,
                      stderr=subprocess.PIPE,
                      universal_newlines=True,
                      timeout=6)

pprint.pprint(proc.stdout) # standard output
pprint.pprint(proc.stderr) # error output
pprint.pprint(proc.returncode) # exit status
```

In the first case the regular val3dity console output is stored in `stdout`, but the verbose description triggered by `--verbose` ends up in `stderr` as if it was an error message. Is this something that you can influence in val3dity?

Additionally, the exit status that is stored in `returncode` is `1`, even though the process completed successfully, and the input is valid. Equally, val3dity returns `1` on invalid input. This is not to say that the validity of the input should influence the exit status, that is reported by the error codes. But also in the second case where val3dity exits with an error, the exit status is `1`.

Shouldn't all successfully terminated processes return `0` and the rest is anything else?

A segmentation fault returns `-11` which is alright I think, couz its negative.

**Comment by hugoledoux** [comment]
returncode should always be 0 indeed, even if the file is invalid since the program completed correctly. I just fixed it: f5b5003c4d3f335bb4f453aaadbe9f10ddc4662a

for iostreams, what I use (std::clog) is apparently redirected to stderr, as std::cerr is (which I don't use at all). See https://stackoverflow.com/a/16772906
Notice that if you don't declare `--verbose` then std::clog goes into a log file `val3dity.log`
