### ISSUE TITLE
'--information' message on non-CityGML files

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#81]
Currently the `--information` options has 3 different outputs:

1. on CityGML input the file summary/statistics is output
2. on GML input the following is output:

```
$ ./val3dity -i ../data/test_empty/empty_primitive.xml 

Information about input file, ignoring all other options.
Reading file: ../data/test_empty/empty_primitive.xml
File does not have the CityGML namespace. Abort.

```
3. on OFF, OBJ input the following is output:

```
$ ./val3dity -i ../data/test_empty/empty_primitive.obj

Statistics/information only GML files.
```

Would it make sense to merge 2 and 3 into a message sth like below?

`Statistics/information only for CityGML files.`

Although the info that `File does not have the CityGML namespace.` is quite informative too in case the user thought that it has a citygml file...

**Comment by hugoledoux** [comment]
I removed --info option for time being: c4b33fc9d4167aeafb39efa4a23a3b88e1494b79

Might bring it back for all types, but in the meantime the use of [citygmlinfo](https://github.com/tudelft3d/citygmlinfo)
