### ISSUE TITLE
An empty OBJ file reports 902, an empty OFF file report 901

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#85]
There are completely empty files in `pytest -k "completely_empty" -v`. All but the OBJ reports 901. It probably doesn't matter much whether the error is 901 or 902, but i think is should be consistent for the GML-JSON group and for the OBJ-OFF(-POLY) group. But if we consider that OBJ can hold multiple objects too, then probably it should belong to the GML-JSON group, thus 901 would be more appropriate.

**Comment by hugoledoux** [comment]
you're right, it should be 902.

Fixed: 121ac7b0a811654d2d52bf994a1d4c75b78c5ed1
