### ISSUE TITLE
CityJSON with duplicate outer shells reports valid

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#86]
Test `pytest -k "402_outer" -v` contains two cityjson files. 
`402_out.json` has a MultiSolid with two identical Solids.
`402_out_1.json` has two identical Solids.
Both reports valid, but I think they should report 402.

**Comment by hugoledoux** [comment]
no they shouldn't. 402 for for duplicated shells in *one* Solid. 

A MultiSolid is a collection of Solids, but the topological relationships between them are not prescribed at all, they can be duplicated. It's just a list of Solids.

Second case: 2 different City Objects having different IDs can have the same geometry as far as val3dity is concerned. Is it "valid"? Perhaps not, but not in val3dity scope at this point... perhaps in the future though.
