### ISSUE TITLE
Inner shell is outside but its face it thouching the exterior

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#87]
In case of a pyramid cavity that is completely outside of the outer shell of a cube, but one face is adjacent to it, an error 401 is reported. I think this is alright, even though the inner shell is completely outside of the exterior. What do you think @hugoledoux ?

My reasoning is that in case the inner shell is moved away from its exterior, the error would become 403. In case the inner shell is moved completely inside its exterior, the error is resolved.

**Comment by hugoledoux** [comment]
its interior is outside but its boundary touches, so 401 is better IMO.
Same if only was touching at one point. Outside means disconnected, that
should be added to doc
