### ISSUE TITLE
Disconnected interior reports valid

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/val3dity#88]
Test 404 is inspired by the Fig.8 in the Validation of 3d geoms... chapter in the Encycolpedia of GIS, 2nd ed. It test three variations of the geometry in the attached pic. 

Version on the pic: reports valid
Version with inner shell touching bottom surface: reports 104
Version with inner shell touching both bottom and top surf: reports valid

Shouldn't they all be 404?
![404](https://user-images.githubusercontent.com/7190603/31381661-7c0a6676-adb5-11e7-9b92-e9604a13617b.jpg)

**Comment by hugoledoux** [comment]
404 is for when there are no intersections between the shells and the interior is disconnected. 

case 1: the interior is still connected, ie I can "walk" from everywhere to everywhere w/o going outside. A case for 404 is in "old" /data/poly/ folder:
```
./val3dity cube.poly --ishell blocker1.poly
