### ISSUE TITLE
Error Type 302 not showing exact error location and Snapping Tolerance 0.001m not considering

### ISSUE THREAD

**Issue by mjaggala** [tudelft3d/val3dity#99]
[302_GML_DGN_Snaps.zip](https://github.com/tudelft3d/val3dity/files/1404053/302_GML_DGN_Snaps.zip)
Val3dity reporting error type 302, but we are unable to locate exact error location in the Building. 
In the attached Sample building all surfaces are snapped with in the snapping tolerance 0.001m. Val3dity not considering this snapping tolerance while validate the data. Even all snapped perfect, still the val3dity reporting 302 error.  Please review the attached DGN, GML with Val3dity log files and provide a solution.

**Comment by hugoledoux** [comment]
thanks for that case. 

I looked at it and indeed the merging/snapping wasn't properly done, and it was a bug. The large coordinates in Rotterdam and my faulty algo to merge made that with that case 2 vertices that are 0.1mm apart were separate, and thus a hole was reported.

I fixed it (not in master branch, it'll be in "v2" when I have tested it more) and it's fixed. Your solid has no hole (but the surfaces are not planar, one needs to apply a 2cm tolerance).

**Comment by mjaggala** [comment]
Hi Hugoledoux,
Thanks for the explanation. We are waiting for the v2 version. 
We applied planarity tolerance of 3cm already. please check attached val3dity settings snap. 
![val3dity](https://user-images.githubusercontent.com/32330491/31995098-b94b2e52-b9a0-11e7-9a9f-a413aa36f882.JPG)

Thanks you,
Manoraju.

**Comment by hugoledoux** [comment]
No need to wait, it’s there on the repository:
https://github.com/tudelft3d/val3dity/tree/v2
<https://github.com/tudelft3d/val3dity/tree/v2?files=1>

And ready to use I reckon.

You do need to compile it yourself though, but that’s not difficult.
